title: Sravani Mandalika
description: <p align="center">

  <br>   
  I worked as a Program Analyst for 2 years in Cognizant Technology Services.
  I learned Android development and developed few mobile apps and one app is live in the Google Play Store.
  <br>
  <a href="https://github.com/sravani-mandalika">GitHub</a>
  </p>
  
theme: jekyll-theme-merlot
