title:title: Merlot theme
description: Merlot is a theme for GitHub Pages.
title: Sravani Mandalika
description: <p align="center">
  <a href="https://github.com/sravani-mandalika">GitHub</a>

  <br>   
  I worked as a Program Analyst for 2 years in Cognizant Technology Services.
  I learned Android development and developed few mobile apps and one app is live in the Google Play Store.
  <br>
  </p>
show_downloads: true
google_analytics:
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot
